drivers/include/nrfx_adc.h, drivers/src/nrfx_adc.c
Commit removes line with deprecated and no longer supported assertion in
nrfx_adc driver. Documentation is aligned to this change to provide clear
information.
=> nrfx_adc: Remove deprecated assertion

drivers/src/nrfx_saadc.c
Correcting format to %s for the __func__ parameter which is of
const * char.
=> nrfx_saadc: Correcting format for logging statement.

drivers/src/nrfx_rtc.c
This patch updates the format used in NRFX_LOG* statements with a %lu (long-unsigned)
instead of %d (int) on the places where a uint32_t is passed as argument.
Example error during compilation:
nrfx_rtc.c:324:24: error: format '%d' expects argument of type 'int',
but argument 3 has type 'uint32_t {aka long unsigned int}'
=> nrfx_rtc: Update logging format to use %lu instead of %d

drivers/src/nrfx_timer.c
This patch updates the format used in NRFX_LOG* statements with a %lu (long-unsigned)
instead of %d (int) on the places where a uint32_t is passed as argument.
=> nrfx_timer: Update logging format to use %lu instead of %d

hal/nrf_ecb.h
Commit adds hardware access layer in nrf_ecb.h. Layer is similar to other
implementations to keep sources consistent. Documentation is aligned to
meet current implementation.
Previous implementation is kept and will be removed in next major release.
=> nrf_ecb: Add hardware access layer in nrf_ecb.h

drivers/src/nrfx_twi.c
In order to send and receive more than 255 bytes in one transaction
this patch increases the size of the length parameters such that
data buffers larger than 255 bytes can be transferred in a single
transaction.
Also, this patch increases the HW_TIMEOUT define by a multiple of 10
to make sure that large transactions are not stopped early by timeout.
=> nrfx_twi: Increase tx and rx transfer length

drivers/src/nrfx_spim.c
Commit fixes situation when Slave Select is set as unused. Configuration
value was not assign to field in control block and slave select field's
value remained zero. It caused pin toggling during SPI transmission when
GPIO 0 is configured as output.
=> nrfx_spim: Fix Slave Select initialization

hal/nrf_ppi.h
Added a function to enable several channels simultaneously.
Similar to the already existent nrf_ppi_channels_disable().
Signed-off-by: Alberto Escolar Piedras <alpi@oticon.com>
=> HAL PPI: add function to enable a set of channels

drivers/nrfx_common.h
This macro does the same thing that the nrfx_get_irq_number() function does.
The difference is that the macro can be used in places where a function call
is not suitable, e.g. in a structure initialization.
Fixes #18.
=> nrfx_common: Add NRFX_IRQ_NUMBER_GET macro

doc/drv_supp_matrix.dox, doc/nrf51_series.dox, doc/nrf52810.dox, doc/nrf52832.dox, doc/nrf52840.dox, doc/nrfx_api.dox, hal/nrf_ccm.h
This is a continuation of the work started by @aescolar-ot and replaces his PR #26.
Added functions for accessing all remaining registers in the CCM peripheral to provide a complete solution.
=> hal: Add HAL for the CCM peripheral

doc/drv_supp_matrix.dox, doc/nrf51_series.dox, doc/nrf52810.dox, doc/nrf52832.dox, doc/nrf52840.dox, doc/nrfx_api.dox, hal/nrf_radio.h
Add the RADIO HAL for the nRF SoCs. Supported SoCs:
- nRF51 series
- nRF52810
- nRF52832
- nRF52840
=> hal: Add HAL for the RADIO peripheral

hal/nrf_gpio.h
This patch adds a new function to read the direction
configuration of a pin.
=> nrf_gpio: Add function for reading pin direction

CHANGELOG.md, drivers/src/nrfx_twim.c
TXRX transfer was missing triggering RESUME task. When previous
transfer ended up without stop condition TWIM is in suspend state.
It is required to resume before starting next transfer.
Fixes #32
=> nrfx_twim: fix resuming TXRX transfer

hal/nrf_ppi.h
Added 2 new functions: one for modifying only the event endpoint,
the other to modify only the task endpoint for a given channel.
Signed-off-by: Alberto Escolar Piedras <alpi@oticon.com>
=> nrf_ppi: Add functions to modify only the event or task endpoints

hal/nrf_gpio.h
This patch adds a new function to read the pull mode configuration of a pin.
It was mostly based on #20.
=> nrf_gpio: Add function for reading pin pull mode

drivers/src/nrfx_usbd.c
- Invalid macros for critical section were used in lines 1800 and 1811.
- Unused variable (uint8_t rb) warning if NRFX_USBD_PROTO1_FIX_DEBUG
is defined as 0
Signed-off-by: Paweł Zadrożniak <pawel.zadrozniak@nordicsemi.no>
=> nrfx_usbd: Fix compilation errors/warnings

drivers/src/nrfx_nfct.c
This patch corrects a few things in nrfx_nfct that made it impossible
to compile this driver outside of the nRF5 SDK. These are:
- call to UNUSED_PARAMETER macro
- memcopy() used without including the proper header file
- call to NRF_LOG_INFO macro
=> nrfx_nfct: Make the driver compilable outside of nRF5 SDK

drivers/src/nrfx_uarte.c
In certain cases nrfx_uarte_tx_in_progress() needs to always return true. Such
behavior was observed when nrfx was compiled with strong optimizations (-O3).
Marking tx_buffer_length as volatile solved the problem.
Tested on Linux with arm-none-eabi-gcc v8.2.0
=> nrfx_uarte: Make uarte_control_block_t's tx_buffer_length volatile

drivers/src/nrfx_uart.c
This patch declares the member tx_buffer_length of uart_control_block_t
to be a volatile variable. This variable might be set/read by main thread
and also cleared by IRQ context, which might lead to unexpected behaviour
when compiling with high optimization level (LTO + O3).
=> nrfx_uart: Declare tx_buffer_length to be volatile.

templates/nRF51/nrfx_config.h, templates/nRF52810/nrfx_config.h, templates/nRF52811/nrfx_config.h, templates/nRF52832/nrfx_config.h, templates/nRF52840/nrfx_config.h
I noticed that the UART0 enable config is not using the right annotation. It is using a number entry but it should be using a boolean entry.
=> templates: Fix config type for UART0 enable

drivers/src/nrfx_wdt.c
Attempting to call `nrfx_wdt_init` with a `reload_value` over that of 131072 will cause a `uint32_t` overflow causing the `reload_value` to be set much lower then intended.
Promoting this calculation to a `uint64_t` resolves this issue
For what it's worth I think `reload_value` should be renamed to `reload_value_ms` to make its use more obvious as at glance one would assume this directly sets `NRF_WDT->CRV`
=> nrfx_wdt: Fix reload value calculation overflow for large values

drivers/include/nrfx_pwm.h, drivers/src/nrfx_pwm.c
We need to configure gpio pins differently from its default values while initiate pwm and pwm doesn't allow us. The new macro is added so that a user can configure the pins before invoking nrfx_init_pwm if NRFX_PWM_USER_CONFIG_GPIO is set to non-zero.
=> nrfx_pwm: Make possible to skip GPIO configuration in nrfx_pwm_init()

drivers/src/nrfx_rtc.c, drivers/src/nrfx_timer.c
To avoid warnings about providing an argument of type `uint32_t` (which
is `unsigned int`) where a `long unsigned int` one is expected.
Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>
=> drivers: Cast `uint32_t` arguments to `unsigned long` in log messages

drivers/include/nrfx_nvmc.h, drivers/src/nrfx_nvmc.c
Fix some limitations in the driver relating to the HW:
- The assert triggers for writes to UICR, since it is outside regular flash.
- The OTP region is centered around halfwords.
Found while working on https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1917.
=> NVMC improvements for UICR/OTP

drivers/src/nrfx_spim.c
Log message references non existing p_instance variable, changed to
p_spim.
Signed-off-by: Mieszko Mierunski <mieszko.mierunski@nordicsemi.no>
=> nrfx_spim: Fix error log message.

drivers/src/nrfx_nvmc.c
In SoCs with TrustZone support, only secure code can access UICR.
When a non-secure target is built, the NRF_UICR symbol is not even
defined.
This commit prevents the NVMC driver from referencing the NRF_UICR
symbol when the driver is compiled for a non-secure target.
Assertions that normally use this symbol for checking if a given
address is valid for an operation on flash will fail in non-secure
code when the supplied address belongs to the UICR region, what is
the expected behavior.
Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>
=> nrfx_nvmc: Prevent use of NRF_UICR symbol in non-secure targets

drivers/src/nrfx_nvmc.c
For secure code, the access mode needs to be set for both secure and
non-secure regions. Otherwise, attempts from secure code to write or
erase a region configured as non-secure end up with BusFault.
Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>
=> nrfx_nvmc: Fix setting of program memory access mode for secure code

drivers/src/nrfx_twi.c, drivers/src/nrfx_twim.c
This is necessary so that next occurence of nrfx_{twi, twim}_enable()
followed by {twi, twim}_xfer() will not raised a NRFX_ERROR_BUSY error.
This could happen when a previous transfer is started but is aborted
using nrfx_{twi, twim}_disable() before the end of the transaction which
calls {twi, twim}_irq_handler().
Signed-off-by: Xavier Chapron <xavier.chapron@stimio.fr>
=> drivers: nrfx_{twi, twim}: Fix busy flag not reset

drivers/src/nrfx_dppi.c
Depending on the implementation of NRFX_CRITICAL_SECTION_ENTER
the 'channel' variable could be undefined in logging function.
Signed-off-by: Nikodem Kastelik <nikodem.kastelik@nordicsemi.no>
=> nrfx_dppi: Fix variable used in logging function

drivers/include/nrfx_nvmc.h
Add a workaround function for accessing UICR safely without being
affected by PAN 7.
This workaround and bug is described in errata for nrf91 with ID "[7]
KMU: Subsequent accesses between info_mem and main_mem of the flash
may not work properly".
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
=> nrfx: uicr: Add workaround function for PAN 7

drivers/src/nrfx_pwm.c
The whole pin configuration function in the driver should be skipped
when both GPIO and PSEL skip flags are set, but the code that checks
this condition, despite the comment correctly explaining its purpose,
contains an unwanted negation. This commit fixes this embarrassing
copy-paste mistake.
Mirrored https://github.com/zephyrproject-rtos/hal_nordic/pull/109.
=> nrfx_pwm: Fix incorrect check that suppresses pin configuration

drivers/include/nrfx_nfct.h, drivers/src/nrfx_nfct.c, hal/nrf_nfct.h
This is a combination of some changes done by nitz in PR:s #79 and #78 that haven't been merged in over a year, so I am trying to get them merged here instead.
I have also added some functions to get/set RFU bits of the SELRES register, which is required by some NFC protocols.
=> nfct: Improve support for various NFC protocols

drivers/include/nrfx_qspi.h, drivers/src/nrfx_qspi.c
Keep the line high during the custom instruction transfer. Otherwise,
its low level can be interpreted by the memory chip as an active
HOLD#/RESET# signal and in consequence the memory status can be read
incorrectly.
Add also related notes to descriptions of nrfx_qspi_cinstr_xfer() and
nrfx_qspi_lfm_start() to warn users that the default configuration
provided by NRFX_QSPI_DEFAULT_CINSTR() may not always be suitable.
Mirrored https://github.com/zephyrproject-rtos/hal_nordic/pull/116.
=> nrfx_qspi: Correct IO3 line level used in nrfx_qspi_mem_busy_check()

hal/nrf_clock.h
This commit disables the array bounds warning (`-Warray-bounds`) for
the `nrf_clock_is_running` function because GCC 12 and above may report
a false positive due to the size of the write access to the memory
address pointed by the `p_clk_src` argument being variable depending on
the value of the `domain` argument.
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
NOTE: Upstream PR for https://github.com/zephyrproject-rtos/hal_nordic/pull/121
=> nrfx_clock: Disable array bounds warning for nrf_clock_is_running

mdk/nrf91_erratas.h, mdk/system_nrf91_approtect.h
Apply corrections that make it possible to disable APPROTECT mechanism (which is enabled by default in hardware) on the nRF91 Series SiPs.
These are temporary changes supposed to be overwritten by the next update of MDK.
Mirrored https://github.com/zephyrproject-rtos/hal_nordic/pull/130.
=> nrfx: mdk: Fix handling of APPROTECT on nRF91
